### ISSUE TITLE
[Feature] Key to duplicate as private

### ISSUE THREAD

**Issue by AdamPS** [Skeletonxf/duplicate-tab#13]
It's very nice to be able to duplicate to a private window.  However it is a shame that I have to press Alt-Shift-A then tab then enter.  Please could we have a way to set a key to do it directly?

**Comment by Skeletonxf** [comment]
I started developing the ALT+SHIFT+A menu to avoid having loads of shortcuts to memorise!

I added the tabbing so users would be able to use each of the functions from just the keyboard but I suppose as I add more functions to the menu the tabbing won't scale very well either. I should be able to add shortcuts to each of the functions in the ALT+SHIFT+A webpage so that you could do ALT+SHIFT+A, 2 instead of ALT+SHIFT+A, Tab, Enter for example.

![adv-dup-mock](https://user-images.githubusercontent.com/13869843/56498844-755b5700-64fb-11e9-96b9-d0ff1c20819a.png)

It might be able to look something like this, where pressing 1 or N would activate the first function and pressing 2 or P would activate the second. This would reduce the keystrokes for any function to 4 rather than 3 + position in list and ensure that all the keys to press would be on the same side of the keyboard.

Would this method be acceptable?

**Comment by AdamPS** [comment]
Sure, having shortcut keys would be a useful improvement.

**Comment by AdamPS** [comment]
PS It's a nice add-on, thanks for your work!

**Comment by Skeletonxf** [comment]
I know it's a year late, but this feature is now published on AMO in version 2. I actually finished the coding last October but the review system was rejecting my code due to bugs in its syntax linter.

**Comment by AdamPS** [comment]
Great thanks!
