### ISSUE TITLE
Duplicate Tab no longer working

### ISSUE THREAD

**Issue by efouquet** [Skeletonxf/duplicate-tab#17]
Firefox version: 95.0.2 (64-bit)
OS: MacOS Big Sur 11.6.2

When I right click on a tab and select "Duplicate Tab" it does nothing at all. 

From the Firefox browser console, I'm seeing that just right clicking on a tab is raising an uncaught exception and when selecting "Duplicate Tab" another error is raised. I'm assuming that perhaps "Duplicate Tab" is a victim of the first exception here? 

Here's the console output:
[console-export-2022-1-5_9-31-0.txt](https://github.com/Skeletonxf/duplicate-tab/files/7815947/console-export-2022-1-5_9-31-0.txt)

**Comment by Skeletonxf** [comment]
Hi

Thanks for the bug report

Are you sure you are using the context menu on the tab that comes from Duplicate Tab and not Firefox natively?
The 'Duplicate Tab' entry with both words capitalised near the top of the context menu is native to Firefox and not part of the Duplicate Tab extension
https://github.com/Skeletonxf/duplicate-tab/blob/master/settings/duplicate-context-menu-screenshot.png

Also, can you still duplicate your tab from a keyboard shortcut? You may need to go to 'Manage Extension Shortcuts' to check what the default shortcut is mapped to on MacOS

**Comment by efouquet** [comment]
Hello,

Well, originally I was using the native Firefox "Duplicate Tab" as your surmised, but based on your reply I decided to add your extension to see if that resolves this for me, but I still get an error when using your functionality. 
Here's a new browser console output:
[console-export-2022-1-5_11-55-6.txt](https://github.com/Skeletonxf/duplicate-tab/files/7816850/console-export-2022-1-5_11-55-6.txt)

The first error is when I right-click the tab, just like before, the second one is when I select "Duplicate Tab --> Duplicate":
![Screen Shot 2022-01-05 at 12 04 18 PM](https://user-images.githubusercontent.com/15145250/148266657-e4c8d88d-2151-4fb0-a637-23342f8b74f6.png)

**Comment by Skeletonxf** [comment]
I don't think I can help you unfortunately.

If the native Duplicate Tab context menu in Firefox doesn't work on your installation then that's likely also breaking the API Duplicate Tab (the addon) uses. You may want to try installing a new version of Firefox such as Firefox beta or Firefox developer edition since it's plausible something in your browser profile broke the functionality, and a fresh install might not be affected. If the issue doesn't occur on another installation of Firefox you may need to reset some of your browser's [profile data](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data). If you can reproduce this on a fresh installation of Firefox you may need to open a bug report to Mozilla directly.

**Comment by efouquet** [comment]
Sounds good, thanks.

**Comment by efouquet** [comment]
Fresh install worked :)
