### ISSUE TITLE
REQ: Idk if anyone sees this anymore, but great addon that is gonna get real useful. One small REQ for convience? I know its a shot in the dark,

### ISSUE THREAD

**Issue by TimmyP777** [Skeletonxf/duplicate-tab#22]
Since youtube is using anti adblock, you can simply view videos in a private window by right clicking on them. However, going to the blocked video, and duplicating the tab in private mode allows it to remain in browser history, keep the "blocked" window open so you can comment, and the private one open so you can view the video and even use addons.

I think this is gonna be the easiest solution, and since this plugin provides the easiest way to do this- by right clicking the opened tab, advanced duplicate (with this addon set up), and selecting open in private window...

Can you remove that extra step, and just make a way to duplicate the current tab in a private window?

I know this hasnt been updated in a year, so I obviously understand if nobody even sees this. This is going to be the solution I ultimately present to people.

**Comment by Skeletonxf** [comment]
This addon hasn't had an update on AMO because I've not added any functionality this year, I still use it and am maintaining it.

If I understand you correctly, you want to open a tab in normal browsing, then duplicate it into a private window and keep the normal browsing tab open? This is already possible to do from just the keyboard if you trigger the advanced duplication shortcut followed by pressing 2. You don't have to do it with the mouse by right clicking the tab to open the context menu. Obviously it is possible to add direct shortcuts to skip the advanced duplication page, but I implemented that page so that a user doesn't have to remember bespoke shortcuts for each additional duplication functionality, it's just the same shortcut followed by a number or letter, so I'd press ALT+SHIFT+A then 2.

It seems like you might just want a solution that lets you reopen a tab without the cookies from your usual browsing, in which case you might find Mozilla's containers addon https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ is more helpful, potentially alongside Cookie AutoDelete to clear the cookies you don't want to keep around https://addons.mozilla.org/en-US/firefox/addon/cookie-autodelete/

Also, opening the tab in a new window isn't truly 'duplicating' it, it's not really any different than selecting the address bar (CONTROL+L,) copying the URL (CONTROL-C), opening a new window (CONTROL+SHIFT+P), selecting the address bar (CONTROL+L), and pasting the URL (CONTROL-V), though obviously doing that manually all the time is a lot of shortcuts to cycle through. Actually duplicating a tab tends to retain more information like where you were scrolled up to but isn't possible when opening a tab in a new window instead so Duplicate Tab only truly duplicates tabs within the same window.

**Comment by TimmyP777** [comment]
Well, it is more of a comfort/usability request. Using the selection window is fast enough going right to advanced duplicate, but if the option(s) on that page were directly accessible from right click on tab, bypassing the selection page... it would provide a safer, easier solution explicitly to help get around Youtubes new force anti-ad quicker.

In case you haven't seen, Youtube is actively deploying and modifying scripts to detect ad blockers such as ublock, and various youtube enhancement plugins like Enhancer, Resumer. It gets to the point where it now says "3 videos left" "2 videos" etc... However, these videos always work in private mode. Duplicating the *current* tab; the blocked video itself... allows it to remain in browser history natively, and given that it is still open while the duplicated tab is also open (one session is logged in, one isn't) you can make comments on the blocked page.

I did set up a keyboard shortcut bound to one of the six custom buttons on my mouse, to open the current window\tab in private... but as a menu driven, mouse-only solution the above would be the perfect solution. I did try Containers earlier, but its simply "too much" for the single task. This is superior as this has less of a footprint, and this is explicitly for Youtube and nothing more.

Thanks for listening and the great addon!

**Comment by Skeletonxf** [comment]
Having continued some migration work on Duplicate Tab today and refamiliarising myself with how it works, I think this feature is not a good fit for the add-on. Duplicate Tab's advanced duplication page has to work out which options are actually available to use for a given tab, as some tabs can't be duplicated or moved into private windows. This code is not particularly complex, but it is not able to run until the user has interacted with the add-on by using the browser icon, context menu, or shortcut at which point Duplicate Tab knows what tab is to be duplicated.

Since Duplicate Tab doesn't request permissions for anything other than the active tab, it wouldn't be able to passively scan the user's tabs in the background to ensure that the context menus always contained only entries for what the user could actually do. It would be possible to list all advanced duplication options at all times on the context menus instead, but this would be confusing for a user as some of them would silently fail when used with no explanation as to why.

Since it's already possible to achieve this with the add-on via shortcuts I don't think the maintenance burden and user experience issues that would come from adding the same functionality to the context menu directly are worth it.

It may be more suitable functionality for a different add-on that already requests permissions for all tabs, though I'm not 100% sure any add-on, even if it passively scanned the user's tabs, could adjust the context menus based on which tab the user right clicked either. I suspect duplicating every YouTube video in a private tab just to watch it will get tiresome no matter what means you use.

**Comment by TimmyP777** [comment]
I suspect duplicating every YouTube video in a private tab just to watch it will get tiresome no matter what means you use.

Not if its the only choice.

Sorry I figured this would simple, because you can pass -private http://url to Firefox.exe and have it open in private.

Thanks anyway. Ill find a way.
