### ISSUE TITLE
Unable to Place duplicated tabs directly after the original

### ISSUE THREAD

**Issue by Cr8zyIvan** [Skeletonxf/duplicate-tab#24]
If you're having problems with Duplicate Tab please specify your operating system and Firefox version (Help -> About Firefox).

Firefox Version 1280.3 (64-bit)
Windows Version Windows 10 Home, 22H2

I'm not sure if the problem comes from Firefox, or perhaps this Extension. However, I am unable to Duplicate Tabs directly after the original. I've tested "Duplicate-Tab"'s options, and I've also gone through the suggested listed Firefox Flags, listed in the options, to make sure they were at "True" (browser.tabs.insertAfterCurrent, & browser.tabs.insertRelatedAfterCurrent).

This seems to be a recent phenomenon.

**Comment by Skeletonxf** [comment]
Are you using the regular duplicate function, ie clicking the addon or using the shortcut? The only way I can reproduce this is by using the advanced duplication page then selecting to duplicate tab, which will sometimes put the tab to the end of the tab row instead of immediately after because it has to create a new tab so the browser doesn't treat the original tab as 'current'.

**Comment by Cr8zyIvan** [comment]
My sincere apologies. I just deactivated two (2x) other Extensions I forgot I installed, that I hadn't tested out. Everything went back to normal. I don't know if the problem came from Sidebery or Tree Stvle Tab, but those are the two that seem to be the culprits.

Sorry for the disturbance 🙏
