### ISSUE TITLE
Feature Suggestion - Duplicate Multiple Tabs

### ISSUE THREAD

**Issue by Cr8zyIvan** [Skeletonxf/duplicate-tab#25]
I would find it useful to be able to Duplicate Multiple Tabs, the Selected Tabs.

Thanks, Cheers!

**Comment by Skeletonxf** [comment]
Hi, could you elaborate on your use case a bit more? Firefox already has a `Duplicate Tabs` entry on the context menu replacing `Duplicate Tab` when multiple tabs are selected. I'm not aware of any built in keyboard shortcut to select multiple tabs at once, I've always used CONTROL+Click at which point I'm using the mouse anyway so can just use the context menu.

**Comment by Cr8zyIvan** [comment]
I often use the Keyboard to execute various different functions. I rarely use the Context Menu, or as little as I can. When the Function I want to execute is one that I use very often (once a month perhaps), I'll go through the Context Menu, but Duplicating Tabs is something I use every day. Right now, I've been Duplicating Tabs one at a time, not always thinking about the Context Menu to be honest.

Also, in all honesty, I don't know how much I would use "Duplicate Multiple Tabs". I would for sure make an effort to use it and develop a muscle memory to it. As far as the user experience goes, whether you only have one Tab Selected or Multiple Tabs Selected, it's the same Keyboard Shortcut to Duplicate. Of course, I know it is always easier to suggest new features than to actually implement them.

Oh! Another bit of information also is that I use a Multi-Button Programmable Mouse, which I assign various different Keyboard Shortcut, depending on which Program is Active. So I either activate regular Functions via the Keyboard, or via the Mouse, depending on where my hands are located at that specific time.

**Comment by Skeletonxf** [comment]
Thanks, I can surmise from what you've said that it is possible to select multiple tabs with just keyboard shortcuts, and hence there is value in having a keyboard shortcut for this.

However it seems like this would be possible but it will require the `tabs` permission (which will display a warning of "Access your data for all websites") rather than the `activeTab` permission Duplicate Tab uses, which comes with no warning as it is less intrusive.

From browsing the docs and some tests, 'selecting' multiple tabs is actually [highlighting](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab#highlighted) them. As the other highlighted tabs aren't active, since there is only the 1 active tab in a window https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/getSelected, the `activeTab` permission won't be able to access them - which is a good thing usually, Duplicate Tab doesn't have access to tabs you don't run it on, but I can appreciate the confusion here since it sure *looks* in the Firefox UI like multiple active tabs at once.

As I've said in previous closed issues so I won't restate everything, I don't want to add the `tabs` permission to this addon because that permission is extremely intrusive for such an addon.

However, this is definitely possible to add or hopefully find in other addons that do request access to all websites, so you might be able to find an alternative on AMO for your use case.
