### ISSUE TITLE
Duplicate tab should follow the "browser.tabs.insertRelatedAfterCurrent" config setting

### ISSUE THREAD

**Issue by dswhite42** [Skeletonxf/duplicate-tab#6]
It would helpful if the duplicated tab honored the **browser.tabs.insertRelatedAfterCurrent** config setting.  That is, put the new tab at the end of the tab list if the setting is "false", rather than placing it directly to the right of the original tab.

Thanks.

**Comment by Skeletonxf** [comment]
I don't believe it is possible to read the browser config settings. It should be easy enough to create a setting for the addon directly for that configuration however.

**Comment by exec228** [comment]
Salut!
Is it possible in 2020 to insert it "aftercurrent" while
>browser.tabs.insertAfterCurrent=false
>browser.tabs.insertRelatedAfterCurrent=false

?

Because duplicate is not "related". It IS the tab :-)

**Comment by Skeletonxf** [comment]
I don't understand what you mean?

**Comment by Skeletonxf** [comment]
This should be technically possible because duplicating a tab via an addon follows the addon APIs and there is an option to specify the new position. I'm assuming setting `browser.tabs.insertAfterCurrent` to false does not affect how Duplicate Tab positions new tabs currently because otherwise this issue would not have been opened.

**Comment by exec228** [comment]
Salut!

1.My browser intentionally opens new tabs (links, bookmarks) at ultimate right. Not aftercurrent.
Thus I have:
browser.tabs.insertAfterCurrent;false
browser.tabs.insertRelatedAfterCurrent;false

2.And on closing tab I don't want jump to OwnerOnClose.
Thus I have:
browser.tabs.selectOwnerOnClose;false

BUT: duplicate is neither "new tab", nor "related tab". It **is the** tab. Just cloned.
I want **duplicate** tab to be inserted right **after original tab**.
Despite settings named, which I have about 15 years that way, and I'm okay with these.

Is it possible?

Thank you!

**Comment by Skeletonxf** [comment]
`browser.tabs.insertRelatedAfterCurrent` is the relevant one here

@dswhite42 despite no change to the addon code it is now respecting this setting on my version of Firefox 78
@exec228 because Firefox is now applying this setting to the duplicated tab, to support every combination there needs to be a three way configurable option

1 - (current behaviour) let the browser choose where the duplicated tab is placed, which follows the `browser.tabs.insertRelatedAfterCurrent` setting
2 - override the choice and always put the duplicated tab just after the original
3 - override the choice and always put the duplicated tab at the end

Adding support for 2 and 3 are both definitely possible but will require a bit of work to keep track of the indexes of the tabs

**Comment by exec228** [comment]
Understood.
Thank you for reply!

**Comment by Skeletonxf** [comment]
Just as a disclaimer I currently have no way to test addons on mobile due to the state of Firefox for Android so even if I finish the code for this soon it might be a while before I release to addons.mozilla.org

**Comment by Skeletonxf** [comment]
This has now been implemented and released on AMO as version 2.2
