### ISSUE TITLE
Can "Switch focus on duplicate" happen immediately?

### ISSUE THREAD

**Issue by dswhite42** [Skeletonxf/duplicate-tab#7]
Hi - once again, this is a great extension and I appreciate your making it, Skeletonxf.

Would it be possible to make "Switch focus on duplicate" occur immediately?  Otherwise, I click the button and then (if it's a slow page to load) wait a while, and then perhaps start working on a different tab.  Then, maybe 10-30 seconds later (or more), suddenly I'm pulled back to the duplicated tab.

If the focus change happens immediately, I can decide whether to wait (if I see the duplicate tab is loading quickly) or else change focus back to another tab (and be assured that the focus won't be pulled away a few seconds later).

Thanks.

**Comment by Skeletonxf** [comment]
Apologies for the delay. I've been rather busy.

This was the first review/request on amo and I looked into it then and couldn't find a way to make it happen quicker. Now you can see here

https://github.com/Skeletonxf/duplicate-tab/blob/70a0fd0df31e590ca195a647d811cd038384744b/background.js#L20-L27


that newer versions of Firefox switch focus immediately, instead of on page load. I've done a quick test on the long term support 52 Firefox and I can reproduce the long delay.

Fortunately you can already toggle off switch focus on duplicate in the addon settings and manually switch over to the duplicate tab when you want to so you don't get pulled away.

The next ESR v60 Firefox which appears to already be [out](https://www.mozilla.org/en-US/firefox/organizations/) will switch focus on duplicating tabs automatically, before page load. This has been the behaviour of many of the last Firefox versions. I'm not sure which version the behaviour changed in, probably some time around that commit creating the toggle.
